image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 8.14.0
  GH_TOKEN:
    secure: JQTogieeX60CDa5l+4NGvmE3do+t8iDPrrppjHYfGbx2vlGMvNUtPbJvnsqZ07tF

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> package.json
  - app/node_modules -> app/package.json
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off
# deploy:
#   release: v$(appveyor_build_version)
#   description: 'Features'
#   provider: GitHub
#   auth_token:
#     secure: 'JQTogieeX60CDa5l+4NGvmE3do+t8iDPrrppjHYfGbx2vlGMvNUtPbJvnsqZ07tF' # your encrypted token from GitHub
#   artifact: /.*\.exe/            # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                 # release from master branch only
#     appveyor_repo_tag: true
version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  # NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
  # - yarn global add greenkeeper-lockfile@2
  - npm run setup
  - npm run build-dll
  - npm run package

# NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
# before_test:
#   - greenkeeper-lockfile-update

test_script:
  - node --version
  # - yarn lint
  - yarn package
  # - yarn test
  # - yarn test-e2e

# NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
# after_test: greenkeeper-lockfile-upload
